### ISSUE TITLE
actix-web 3.0

### ISSUE THREAD

**Issue by clux** [getsentry/sentry-rust#143]
Hey! First of all, thanks a lot for all these popular integrations. Really makes sentry a breeze to use in rust.

Been trying the [actix-web 1.0 rc](https://docs.rs/crate/actix-web/1.0.0-rc) that recently came up. Judging by their [1.0 migration guide](https://github.com/actix/actix-web/blob/master/MIGRATION.md#10) middleware should just be mounted slightly differently:

> instead of
```rust
    let app = App::new()
         .middleware(middleware::Logger::default())
```
> use .wrap() method
```rust
    let app = App::new()
         .wrap(middleware::Logger::default())
```

but there does appear to be more to it under the hood because the sentry middleware is the last thing for me that fails during the migration:

```rust
    .wrap(sentry_actix::SentryMiddleware::new())
```

>    |             .wrap(sentry_actix::SentryMiddleware::new())
>    |              ^^^^ the trait `actix_service::transform::IntoTransform<_, <impl actix_service::NewService as actix_service::NewService>::Service>` is not implemented for `sentry_actix::SentryMiddleware`

Haven't looked into what's actually needed to fix this here, but hopefully it's an easy impl :pray:

**Comment by Jake-Shadle** [comment]
It's a little more involved unfortunately, as they've completely changed how middleware works, as well as many API changes that makes this more difficult than I had wanted. There is also https://github.com/actix/actix-web/pull/681 which is a problem since a lot of error information, particularly backtraces, is now lost by the time sentry wants to post errors.

**Comment by Jake-Shadle** [comment]
Oh, and here's a WIP branch that gets at least most of the way. https://github.com/EmbarkStudios/sentry-rust/commit/ea827a627d890e1cd510484e0eca0a02deca4c86

**Comment by mitsuhiko** [comment]
So I started looking into this now and the fact that those errors are no longer Fails makes it pretty hard to do useful error reporting here. Not sure what we can do atm.

**Comment by repi** [comment]
A small side note, we at Embark moved away from using `actix-web` to just use `hyper` directly to reduce complexity & amount of dependencies, so no longer need this.

**Comment by pandaman64** [comment]
I'm interested in implementing this. What's the main blocker?

**Comment by jan-auer** [comment]
@pandaman64 The last time we checked the blocker was that there was no nice way to get the route name from Actix in order to print the transaction label. There's a partial implementation that lives here, and that could be ported: 

https://github.com/getsentry/symbolicator/blob/f1b4285b94371a8f57f97509e2d6d3e9687463ba/src/middleware/sentry.rs

Also, this uses `SentryFutureExt`, which we were thinking about porting over to the Sentry SDK:

https://github.com/getsentry/symbolicator/blob/f1b4285b94371a8f57f97509e2d6d3e9687463ba/src/utils/sentry.rs

**Comment by ryanmcgrath** [comment]
Could someone from @getsentry comment on this? `actix-web` is one of the de-facto frameworks in the Rust space, and while I understand upstream API changes can be hell, it's super frustrating that there's no movement on this even with people volunteering to look into it who seemingly just need to be pointed in the right direction.

**Comment by gabelerner** [comment]
@jan-auer can you take another look please? https://actix.rs/docs/middleware/ ... maybe you're able to implement on 2.0?

**Comment by OskarPersson** [comment]
Are there any known blockers now that actix-web 3.0 is out?

**Comment by jan-auer** [comment]
No blockers, and this is still on our backlog. At the moment, we're still working on fixing some issues in the new API and some other integrations. 

However, integrations are designed so that they can be vendored into your application. Since integrations only depend on the public API, you could take the [existing integration](https://github.com/getsentry/sentry-rust/blob/master/sentry-actix/src/lib.rs) and adapt it to Actix 3 until we get to it.

That said, if you're quicker than us, we'd appreciate a contribution :)

**Comment by robjtede** [comment]
If there's anything missing or required of actix-web to re-enable this feel free to @ me.

**Comment by Daggy1234** [comment]
I would love to be able to use this with Actix-web 3.0

**Comment by Mcat12** [comment]
Another custom integration on Actix 2.0, using `wrap_fn`-style middleware:
https://github.com/mozilla-services/autopush-rs/blob/9b93817776bb7c8f27383185a1b5ce08607a6b35/autoendpoint/src/middleware/sentry.rs

**Comment by Daggy1234** [comment]
Oh wow that looks great @Mcat12 will try and Integrate

**Comment by BartWillems** [comment]
When will this crate be published to crates.io? Because currently it still only has the outdated one.

**Comment by Swatinem** [comment]
We have a few breaking changes lined up for the new version and would like to dogfood them first before we push them out to the general public.

**Comment by devwells** [comment]
following
