### ISSUE TITLE
Premature deprecation and removal of failure

### ISSUE THREAD

**Issue by Diggsey** [getsentry/sentry-rust#313]
The 0.22 release removed the `failure` integration entirely, but the closest alternative (anyhow) does not support backtraces on stable rust.

Integrations should not be deprecated, and certainly not removed, unless there is a suitable replacement.

**Comment by Swatinem** [comment]
The old code is still here in the git history:

https://github.com/getsentry/sentry-rust/blob/1831525555e082480425c2593b1eefa94dc6e100/sentry-failure/src/lib.rs

We decided to just copy-paste the code into the projects directly.

**Comment by jan-auer** [comment]
Part of this reasoning was that failure was flagged in [`RUSTSEC-2020-0036`](https://rustsec.org/advisories/RUSTSEC-2020-0036.html). See also https://github.com/getsentry/sentry-rust/issues/269.

Generally, all of the integrations are designed to only use the public API, so that they can be vendored and modified easily. We could consider adding failure back in if there is continued demand in the community for this.

**Comment by Diggsey** [comment]
> We could consider adding failure back in if there is continued demand in the community for this.

IMO the community has been in too much of a rush to deprecate failure. It's no longer receiving updates but there's also nothing wrong with it. It still does what it always did.

When the `Error` trait gets support for backtraces on stable, and crates have started supporting this, *then* there is a reason to deprecate failure, as it will no longer be following best practices.

> Generally, all of the integrations are designed to only use the public API

That is good to know. Still, copy/pasting code and fixing up imports is not an ideal vendoring workflow.
