### ISSUE TITLE
Reqwest 0.11.1 fails

### ISSUE THREAD

**Issue by tonyshkurenko** [getsentry/sentry-rust#319]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry 0.22.0

### Steps to Reproduce

Sentry depends on reqwest 0.11, which leads to 0.11.1 version (latest for now), which doesn't compile: 
https://github.com/seanmonstar/reqwest/issues/1181

Please, specify 0.11.0 explicitly

### Expected Result

It works

### Actual Result

It fails

**Comment by jan-auer** [comment]
Running `cargo update -p native-tls` solves this on your application. Unfortunately, we don't have control over transitive dependencies. It seems like there will be a new release fixing this soon.

**Comment by tonyshkurenko** [comment]
There is an option to specify 0.11.0 version, instead of using generic 0.11

**Comment by jan-auer** [comment]
We generally do not pin patch versions in a library as that could create duplicate dependencies when the library is being used in an application. This is really an outlier and needs to be fixed in reqwest, and it only occurs when someone is upgrading from an old version to a newer one. If you were to recreate your `Cargo.lock` or simply run `cargo update`, the problem goes away. 

I really think we shouldn't lock into a specific patch version just because of a transient issue in old lockfiles. You have multiple options:

- Run `cargo update`
- If that is too intrusive, run `cargo update -p native-tls`.
