### ISSUE TITLE
Wished for: Something that would let me find out why my client isn't sending anything to the server

### ISSUE THREAD

**Issue by Yoric** [getsentry/sentry-rust#338]
I have a Sentry client (part of a webserver) that should be talking to a Sentry server. The Sentry server is used in production for other projects and works already. The Sentry client seems to initialize properly. However, nothing gets shown on the server.

I'm running my code with `RUST_LOG=debug` and I do not see any output from sentry that could help me.

Is there any way to get some meaningful output?

**Comment by Swatinem** [comment]
Hm, I see the docs are a bit out of date:

https://docs.rs/sentry/0.22.0/sentry/struct.ClientOptions.html#structfield.debug

However this is actually the `debug-logs` feature: https://github.com/getsentry/sentry-rust/blob/c7d53744ba18739cbc8a632ccfd04f6e796375a7/sentry-core/src/macros.rs#L58-L60

Does that help? Otherwise some other reports indicate that some people are using an out-of-date self-hosted version of the sentry server which does not yet support envelopes, so might be good to double check.

**Comment by Yoric** [comment]
Thanks, I'll try that.

> Otherwise some other reports indicate that some people are using an out-of-date self-hosted version of the sentry server which does not yet support envelopes, so might be good to double check.

I suspect that this is the case. How can I confirm?

**Comment by Swatinem** [comment]
> I suspect that this is the case. How can I confirm?

You would need at least Sentry v20.6.0 to work with the latest Rust SDK, otherwise downgrade to `0.19` should help. https://github.com/getsentry/sentry-rust/issues/277#issuecomment-849224422 mentioned that recently.

**Comment by Swatinem** [comment]
@Yoric Did you take a look if this is rather an outdated server? If this continues to be an SDK problem, please re-open.

**Comment by Yoric** [comment]
Apologies, I forgot to respond.
Yes, this is an outdated server, you are right.
