### ISSUE TITLE
Adding request data to Transactions and Spans

### ISSUE THREAD

**Issue by relaxolotl** [getsentry/sentry-rust#443]
Spun off of https://github.com/getsentry/sentry-rust/pull/439. Jess has opened up a PR which adds in basic functionality to include request data with Transactions and Spans, which works quite well. However, it does deviate from what the other SDKs to in order to accomplish the same thing.

Using the Python SDK as an example, [other SDKs use event processors to attach request data to Transactions](https://github.com/getsentry/sentry-python/blob/b63b5ae32d254771cbd027009d0b6def7e2e07fb/sentry_sdk/integrations/wsgi.py#L119-L123). An additional expectation is that integrations handle this under the hood for most users, so in most situations a user should not need to manually attach this data themselves. Besides [the Java SDK](https://github.com/getsentry/sentry-java/pull/1270), most SDKs don't expose request setters and getters on Transactions or Spans. If we stick with the API introduced in #439, this SDK will be deviating from sentry's implicit unified performance API.

Unfortunately, the Rust SDK can't easily extend `event_processor` to follow the example set by other SDKs: While other SDKs model Transactions as Events with a field to differentiate Transactions from "regular" Events (ie inheritance), Transactions and Events are two distinctly separate types in the Rust SDK. 

This issue is meant to capture the discussion and eventual decision regarding what form such an API should look like in this SDK, especially if the conclusion that doing something different from the rest of the other SDKs is worth the tradeoff.

**Comment by smeubank** [comment]
> this SDK will be deviating from sentry's implicit unified performance API.
we do not adhere to the unified performance API, and largely have agreed that it is not something we want to continue following. And instead just follow pragmatic best principle for a given programming language

it has been [marked as deprecated](https://develop.sentry.dev/sdk/miscellaneous/unified-api/) accordingly.

I think this issue is more of a discussion, I will close it for now

If there is interest to reopen. We can disregard the unified API and focus on what problems we want to solve for Rust developers.
