### ISSUE TITLE
Why do Transactions need to have a call to Transaction::finish() - drop(transaction) could do it

### ISSUE THREAD

**Issue by hetoug** [getsentry/sentry-rust#506]
I am trying to do performance measuring on parts of a API-server using `start_transaction(ctx);`
This requires calls to `transaction.finish()` for the transaction-data to be sent to Sentry. Could it not be done when the transaction is dropped by going out of scope as well?
Some transactions have multiple exit points - often error-exits by `?` - and it is complex trying to mash a `transaction.finish()` in everywhere.

The change should be quite small - just implementing the Drop trait for trasnaction,, and having the `drop(transaction)` function calling `transaction.finish()` - or have I overlooked something.

I am willing to make a PR if that is usefiul.

**Comment by Swatinem** [comment]
The problem here is that the transaction can be attached to the scope as well, either directly or indirectly via spans that hold a reference.
The `Transaction` itself is just an opaque wrapper around an `Arc`, there could be references to it floating around anywhere.

Apart from this technical limitation, the Sentry "unified API" kinda mandates this API style, even though it admittedly might not be a good fit for Rust.

**Comment by szokeasaurusrex** [comment]
Given @Swatinem's comment, and the long period of inactivity that has followed, I am going to go ahead and close this issue.

For the reasons @Swatinem listed, we are not planning to implement this change, but if someone would like to propose a PR, we'd gladly consider it.
