### ISSUE TITLE
Is there a trick to use integrations::env_logger and sentry_actix together?

### ISSUE THREAD

**Issue by bbigras** [getsentry/sentry-rust#59]
In some programs I do stuff outside actix-web so I would like to also log error leveled log messages but I get duplicates when I get errors in actix-web.

Is there a trick to exclude "actix_web" from integrations::env_logger?

**Comment by mitsuhiko** [comment]
There is no good way yet but it would make sense to add a way to filter out based on a callback.

**Comment by mitsuhiko** [comment]
For now the best way to solve this is to use a `before_breadcrumb` callback on the options.

**Comment by repi** [comment]
Ran into this today also. 

Have a robust way of setting up such breadcrumb filtering to avoid the duplicates?

**Comment by mitsuhiko** [comment]
@repi is this about a breadcrumb appearing or the event being reported from both `actix_pipeline` and the sentry error handler? (or rather is this for actix at all here)

**Comment by repi** [comment]
We use both the Sentry middleware for actix-web and the Logger middleware. So we both get log output to stdout/stderr as well as crash reporting to sentry.

```rust
        .middleware(SentryMiddleware::new())
        .middleware(Logger::default())
```

But then errors get picked up and reported twice in Sentry, both through the Sentry middleware and through the `Logger` `error!`.

**Comment by mitsuhiko** [comment]
Yap. that makes sense. We need to figure out something here. In other languages we keep the last exception stashed in TLS temporarily so we can see if something already reported it. The same trick does not work here. One way would be to just have a global registry of ignored loggers and then ignore the actix pipeline logger.

**Comment by czifro** [comment]
I first want to disclose I'm new to Rust, Actix, and Sentry. I've used the first two for a bit now, but Sentry is very new. So, please forgive my naivity.

Anyway, since you cache the exception so that it can be checked against to see if it has already been sent within a specified interval, would something like [cached-rs](https://github.com/jaemk/cached) with its timed cache scheme provide you the necessary behavior to mitigate this issue? It was just a thought that came to mind while reading this (but I'm not sure if it is the correct thought).

**Comment by Swatinem** [comment]
Closing this because the logger and actix integrations were complete rewritten some time ago
