### ISSUE TITLE
Use backtrace-parser?

### ISSUE THREAD

**Issue by srijs** [getsentry/sentry-rust#68]
Hi there!

I recently had to solve the problem of parsing backtraces to offer a good integration with `failure` for error reporting (context is my project over at https://github.com/srijs/rust-aws-lambda).

Your workaround here served as inspiration for me to write a `pest`-based parser for backtraces, which should not only be faster but also results in smaller binary sizes by removing the `regex` dependency (something that was important for my lambda use-case).

This is more or less just a heads-up that I published that as [backtrace-parser](https://crates.io/crates/backtrace-parser), and was wondering whether that's something you'd be interested in as well.

I'm aware that the longer-term story here is to move backtrace support into `std` (the start of which is boats RFC to fix the error trait), so please feel free to close this if you feel it's not worth doing!

**Comment by mitsuhiko** [comment]
My plan is to expose the backtrace from failure so that no parsing is needed.

**Comment by mitsuhiko** [comment]
@srijs I started some attempts of wrapping backtrace over here: https://github.com/mitsuhiko/defeat

I also added an issue on failure to work on this: https://github.com/rust-lang-nursery/failure/issues/237

Would love it you can give feedback on the backtrace in defeat. Closing this issue here for the other.
